In [2]:
import pandas as pd
from pathlib import Path
import numpy as np
import os

BASE_DIR = Path().resolve().parents[2]

csv_2020 = BASE_DIR / 'flatfiles' / 'data_vf' / 'data_2020.csv'
csv_2021 = BASE_DIR / 'flatfiles' / 'data_vf' / 'data_2021.csv'
csv_2022 = BASE_DIR / 'flatfiles' / 'data_vf' / 'data_2022.csv'
csv_2023 = BASE_DIR / 'flatfiles' / 'data_vf' / 'data_2023.csv'
csv_2024 = BASE_DIR / 'flatfiles' / 'data_vf' / 'data_2024.csv'
csv_2025 = BASE_DIR / 'flatfiles' / 'data_vf' / 'data_2025.csv'

csv_communes_2022 = BASE_DIR / 'flatfiles' / 'commune_france' / 'communes_france_2022.csv'
csv_communes_2023 = BASE_DIR / 'flatfiles' / 'commune_france' / 'communes_france_2023.csv'
csv_communes_2024 = BASE_DIR / 'flatfiles' / 'commune_france' / 'communes_france_2024.csv'
csv_communes_2025 = BASE_DIR / 'flatfiles' / 'commune_france' / 'communes_france_2025.csv'

csv_taxe_fonciere = BASE_DIR / 'flatfiles' / 'taxe_fonciere_chefs_lieux_2021_2024.csv'

taux_inflation = BASE_DIR / 'flatfiles' / 'taux_inflation.csv'

nbr_emploi_par_region = BASE_DIR / 'flatfiles' / 'nbr_emploi_par_region.csv'

osm_france = BASE_DIR / 'flatfiles' / 'osm_france.csv'

In [4]:
# Création des DataFrames
df_2020 = pd.read_csv(csv_2020)

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Utilisateur\\Desktop\\Geologis\\GeoLogis\\flatfiles\\data_vf\\data_2020.csv'

In [11]:
df_2021 = pd.read_csv(csv_2021)

C:\Users\fatim\AppData\Local\Temp\ipykernel_17292\4291009226.py:1: DtypeWarning: Columns (10,12,14,17,18,20,22,24,35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2021 = pd.read_csv(csv_2021)

In [13]:
df_2022 = pd.read_csv(csv_2022)

C:\Users\fatim\AppData\Local\Temp\ipykernel_17292\66118111.py:1: DtypeWarning: Columns (10,12,14,16,17,18,20,22,35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2022 = pd.read_csv(csv_2022)

In [15]:
df_2023 = pd.read_csv(csv_2023)

C:\Users\fatim\AppData\Local\Temp\ipykernel_17292\2045294576.py:1: DtypeWarning: Columns (8,10,12,14,16,17,18,20,22,26,35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2023 = pd.read_csv(csv_2023)

In [4]:
df_2024 = pd.read_csv(csv_2024)

C:\Users\fatim\AppData\Local\Temp\ipykernel_17212\401764953.py:1: DtypeWarning: Columns (10,12,14,16,17,18,20,22,24,35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2024 = pd.read_csv(csv_2024)

In [8]:
df_2025 = pd.read_csv(csv_2025)

C:\Users\fatim\AppData\Local\Temp\ipykernel_17212\1456618700.py:1: DtypeWarning: Columns (10,12,14,16,17,18,20,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2025 = pd.read_csv(csv_2025)

In [117]:
cols = [
    'date_mutation',
    'valeur_fonciere',
    'surface_reelle_bati',
    'code_commune',
    'type_local',
    'nombre_pieces_principales',
    'longitude',
    'latitude',
    'code_postal',
    'id_mutation'
]

def prepare_and_agg(df):

    os.makedirs('raw', exist_ok=True)
    
    df = df[cols].copy()
    df['prix_m2'] = df['valeur_fonciere'] / df['surface_reelle_bati']
    df['annee'] = pd.to_datetime(df['date_mutation']).dt.year
    
    df_agg = df.groupby(['code_commune', 'annee']).agg({
        'prix_m2': 'mean',
        'surface_reelle_bati': 'mean',
        'id_mutation': 'count'
    }).rename(columns={'id_mutation':'nb_ventes'}).reset_index()
    
    annee= df['annee'].unique()[0] 
    output_path = os.path.join('raw', f'csv_agg_{annee}.csv')
    
    df_agg.to_csv(output_path, index=False, sep=';', encoding='utf-8')
    
    print(f"Fichier CSV enregistré ici : {output_path}")
    return df_agg

In [9]:
df_agg_2020 = prepare_and_agg(df_2020)

Fichier CSV enregistré ici : raw\csv_agg_2020.csv

In [12]:
df_agg_2021 = prepare_and_agg(df_2021)

Fichier CSV enregistré ici : raw\csv_agg_2021.csv

In [14]:
df_agg_2022 = prepare_and_agg(df_2022)

Fichier CSV enregistré ici : raw\csv_agg_2022.csv

In [16]:
df_agg_2023 = prepare_and_agg(df_2023)

Fichier CSV enregistré ici : raw\csv_agg_2023.csv

In [7]:
df_agg_2024 = prepare_and_agg(df_2024)

Fichier CSV enregistré ici : raw\csv_agg_2024.csv

In [9]:
df_agg_2025 = prepare_and_agg(df_2025)

Fichier CSV enregistré ici : raw\csv_agg_2025.csv

In [ ]:
df_agg_2020 = pd.read_csv(r'raw\csv_agg_2020.csv', sep=';')
df_agg_2021 = pd.read_csv(r'raw\csv_agg_2021.csv', sep=';')
df_agg_2022 = pd.read_csv(r'raw\csv_agg_2022.csv', sep=';')
df_agg_2023 = pd.read_csv(r'raw\csv_agg_2023.csv', sep=';')
df_agg_2024 = pd.read_csv(r'raw\csv_agg_2024.csv', sep=';')
df_agg_2025 = pd.read_csv(r'raw\csv_agg_2025.csv', sep=';')

# Concaténer tous les DataFrames
df_agg_all = pd.concat([df_agg_2020, df_agg_2021, df_agg_2022, df_agg_2023, df_agg_2024,df_agg_2025
], ignore_index=True)

In [193]:
df_agg_all

       code_commune  annee      prix_m2  surface_reelle_bati  nb_ventes
0              1001   2020  1508.351938           132.857143         15
1              1002   2020  2022.908835            47.000000         10
2              1004   2020  2530.613622            91.926136        433
3              1005   2020  3277.989223           105.478261         57
4              1006   2020  2326.979167           110.000000         12
...             ...    ...          ...                  ...        ...
195285        30351   2025  3717.700974            95.454545        145
195286        30352   2025  3113.750937           110.130435         61
195287        30354   2025  2230.434783           230.000000          6
195288        30355   2025  2579.066284            99.857143         15
195289        30356   2025  5666.725967            76.904762         39

[195290 rows x 5 columns]

In [7]:
df_agg_all['annee'].value_counts()

annee
2022    33356
2021    33225
2023    33160
2024    33113
2020    31891
2025    30545
Name: count, dtype: int64

In [8]:
df_agg_all.head()

  code_commune  annee      prix_m2  surface_reelle_bati  nb_ventes
0         1001   2020  1508.351938           132.857143         15
1         1002   2020  2022.908835            47.000000         10
2         1004   2020  2530.613622            91.926136        433
3         1005   2020  3277.989223           105.478261         57
4         1006   2020  2326.979167           110.000000         12

In [9]:
output_path = os.path.join('raw', f'csv_agg_all.csv')
df_agg_all.to_csv(output_path, index=False, sep=';', encoding='utf-8')

In [10]:
df_communes_2022 = pd.read_csv(csv_communes_2022)
df_communes_2023 = pd.read_csv(csv_communes_2023)
df_communes_2024 = pd.read_csv(csv_communes_2024)
df_communes_2025 = pd.read_csv(csv_communes_2025)
df_communes_2020 = df_communes_2022.copy()
df_communes_2021 = df_communes_2022.copy()

df_communes_2020['annee'] = 2020
df_communes_2021['annee'] = 2021
df_communes_2022['annee'] = 2022
df_communes_2023['annee'] = 2023
df_communes_2024['annee'] = 2024
df_communes_2025['annee'] = 2025

df_communes_all = pd.concat([
    df_communes_2020, df_communes_2021,df_communes_2022, df_communes_2023, df_communes_2024,df_communes_2025
], ignore_index=True)

output_path = os.path.join('raw', f'csv_communes_all.csv')
df_communes_all.to_csv(output_path, index=False, sep=';', encoding='utf-8')

C:\Users\Utilisateur\AppData\Local\Temp\ipykernel_17012\113993347.py:1: DtypeWarning: Columns (0: code_insee, 1: dep_code, 2: canton_code, 3: epci_code, 4: code_insee_centre_zone_emploi) have mixed types. Specify dtype option on import or set low_memory=False.
  df_communes_2022 = pd.read_csv(csv_communes_2022)
C:\Users\Utilisateur\AppData\Local\Temp\ipykernel_17012\113993347.py:2: DtypeWarning: Columns (0: code_insee, 1: dep_code, 2: canton_code, 3: epci_code, 4: code_insee_centre_zone_emploi) have mixed types. Specify dtype option on import or set low_memory=False.
  df_communes_2023 = pd.read_csv(csv_communes_2023)
C:\Users\Utilisateur\AppData\Local\Temp\ipykernel_17012\113993347.py:3: DtypeWarning: Columns (0: code_insee, 1: dep_code, 2: canton_code, 3: epci_code, 4: code_insee_centre_zone_emploi) have mixed types. Specify dtype option on import or set low_memory=False.
  df_communes_2024 = pd.read_csv(csv_communes_2024)
C:\Users\Utilisateur\AppData\Local\Temp\ipykernel_17012\113993347.py:4: DtypeWarning: Columns (0: code_insee, 1: dep_code, 2: canton_code, 3: epci_code, 4: code_insee_centre_zone_emploi, 5: code_unite_urbaine) have mixed types. Specify dtype option on import or set low_memory=False.
  df_communes_2025 = pd.read_csv(csv_communes_2025)

In [11]:
df_communes_all.columns

Index(['Unnamed: 0', 'code_insee', 'nom_standard', 'nom_sans_pronom', 'nom_a',
       'nom_de', 'nom_sans_accent', 'nom_standard_majuscule', 'typecom',
       'typecom_texte', 'reg_code', 'reg_nom', 'dep_code', 'dep_nom',
       'canton_code', 'canton_nom', 'epci_code', 'epci_nom', 'academie_code',
       'academie_nom', 'code_postal', 'codes_postaux', 'zone_emploi',
       'code_insee_centre_zone_emploi', 'population', 'superficie_hectare',
       'superficie_km2', 'densite', 'altitude_moyenne', 'altitude_minimale',
       'altitude_maximale', 'latitude_mairie', 'longitude_mairie',
       'latitude_centre', 'longitude_centre', 'grille_densite', 'gentile',
       'url_wikipedia', 'url_villedereve', 'annee', 'code_unite_urbaine',
       'nom_unite_urbaine', 'taille_unite_urbaine',
       'type_commune_unite_urbaine', 'statut_commune_unite_urbaine',
       'grille_densite_texte', 'niveau_equipements_services',
       'niveau_equipements_services_texte'],
      dtype='str')

In [12]:
cols_commune = [
    'annee','code_insee', 'nom_standard', 'code_postal',
    'dep_code', 'dep_nom', 'reg_code', 'reg_nom',
    'population', 'densite', 'superficie_km2',
    'latitude_centre', 'longitude_centre','zone_emploi'
]
df_comm = df_communes_all[cols_commune]


df_comm[df_comm['annee'] == 2020].head(10)

,annee,code_insee,nom_standard,code_postal,dep_code,dep_nom,reg_code,reg_nom,population,densite,superficie_km2,latitude_centre,longitude_centre,zone_emploi
0,2020,01001,L'Abergement-Clémenciat,1400.0,01,Ain,84,Auvergne-Rhône-Alpes,779,48.7,16,46.153,4.926,8405.0
1,2020,01002,L'Abergement-de-Varey,1640.0,01,Ain,84,Auvergne-Rhône-Alpes,256,27.1,9,46.009,5.428,8405.0
2,2020,01004,Ambérieu-en-Bugey,1500.0,01,Ain,84,Auvergne-Rhône-Alpes,14134,570.5,24,45.961,5.373,8405.0
3,2020,01005,Ambérieux-en-Dombes,1330.0,01,Ain,84,Auvergne-Rhône-Alpes,1751,106.1,16,45.996,4.912,8434.0
4,2020,01006,Ambléon,1300.0,01,Ain,84,Auvergne-Rhône-Alpes,112,18.9,6,45.750,5.594,8404.0
5,2020,01007,Ambronay,1500.0,01,Ain,84,Auvergne-Rhône-Alpes,2800,81.3,34,46.006,5.358,8405.0
6,2020,01008,Ambutrix,1500.0,01,Ain,84,Auvergne-Rhône-Alpes,762,144.1,5,45.937,5.333,8405.0
7,2020,01009,Andert-et-Condon,1300.0,01,Ain,84,Auvergne-Rhône-Alpes,326,47.6,7,45.787,5.658,8404.0
8,2020,01010,Anglefort,1350.0,01,Ain,84,Auvergne-Rhône-Alpes,1105,38.1,29,45.909,5.795,8416.0
9,2020,01011,Apremont,1100.0,01,Ain,84,Auvergne-Rhône-Alpes,368,25.8,15,46.206,5.658,8425.0

#### Merge par code commune

In [108]:
df_vf = pd.read_csv(r'raw\csv_agg_all.csv', sep=';')
df_comm = pd.read_csv(r'raw\csv_communes_all.csv', sep=';')

C:\Users\Utilisateur\AppData\Local\Temp\ipykernel_1580\3494460096.py:2: DtypeWarning: Columns (0: code_insee, 1: dep_code, 2: canton_code, 3: epci_code, 4: code_insee_centre_zone_emploi, 5: grille_densite, 6: code_unite_urbaine, 7: nom_unite_urbaine, 8: type_commune_unite_urbaine, 9: statut_commune_unite_urbaine, 10: grille_densite_texte, 11: niveau_equipements_services_texte) have mixed types. Specify dtype option on import or set low_memory=False.
  df_comm = pd.read_csv(r'raw\csv_communes_all.csv', sep=';')

In [109]:
print(df_vf['annee'].value_counts().sort_index())

annee
2020    31891
2021    33225
2022    33356
2023    33160
2024    33113
2025    30545
Name: count, dtype: int64

In [110]:
cols_commune = [
    'annee','code_insee', 'nom_standard', 'code_postal',
    'dep_code', 'dep_nom', 'reg_code', 'reg_nom',
    'population', 'densite', 'superficie_km2',
    'latitude_centre', 'longitude_centre','zone_emploi'
]
df_comm = df_comm[cols_commune]

In [111]:
df_comm.columns

Index(['annee', 'code_insee', 'nom_standard', 'code_postal', 'dep_code',
       'dep_nom', 'reg_code', 'reg_nom', 'population', 'densite',
       'superficie_km2', 'latitude_centre', 'longitude_centre', 'zone_emploi'],
      dtype='str')

In [112]:
df_vf.columns

Index(['code_commune', 'annee', 'prix_m2', 'surface_reelle_bati', 'nb_ventes'], dtype='str')

In [113]:
df_vf['code_commune'] = df_vf['code_commune'].astype(str).str.zfill(5)
df_comm['code_insee'] = df_comm['code_insee'].astype(str).str.zfill(5)

df_merged = df_vf.merge(df_comm,
                              left_on=['code_commune', 'annee'],
                              right_on=['code_insee', 'annee'],
                              how='left')

In [114]:
df_merged.shape

(195290, 18)

In [115]:
df_merged.head()

,code_commune,annee,prix_m2,surface_reelle_bati,nb_ventes,code_insee,nom_standard,code_postal,dep_code,dep_nom,reg_code,reg_nom,population,densite,superficie_km2,latitude_centre,longitude_centre,zone_emploi
0,01001,2020,1508.351938,132.857143,15,01001,L'Abergement-Clémenciat,1400.0,01,Ain,84.0,Auvergne-Rhône-Alpes,779.0,48.7,16.0,46.153,4.926,8405.0
1,01002,2020,2022.908835,47.000000,10,01002,L'Abergement-de-Varey,1640.0,01,Ain,84.0,Auvergne-Rhône-Alpes,256.0,27.1,9.0,46.009,5.428,8405.0
2,01004,2020,2530.613622,91.926136,433,01004,Ambérieu-en-Bugey,1500.0,01,Ain,84.0,Auvergne-Rhône-Alpes,14134.0,570.5,24.0,45.961,5.373,8405.0
3,01005,2020,3277.989223,105.478261,57,01005,Ambérieux-en-Dombes,1330.0,01,Ain,84.0,Auvergne-Rhône-Alpes,1751.0,106.1,16.0,45.996,4.912,8434.0
4,01006,2020,2326.979167,110.000000,12,01006,Ambléon,1300.0,01,Ain,84.0,Auvergne-Rhône-Alpes,112.0,18.9,6.0,45.750,5.594,8404.0

In [116]:
df_taxe_fonciere = pd.read_csv(csv_taxe_fonciere) 
df_taxe_fonciere.head(10)

df_taxe_2025 = df_taxe_fonciere[df_taxe_fonciere['annee_cible'] == 2024].copy()
df_taxe_2025['annee_cible'] = 2025

df_taxe_fonciere = pd.concat([df_taxe_fonciere, df_taxe_2025], ignore_index=True)

df_taxe_2020 = df_taxe_fonciere[df_taxe_fonciere['annee_cible'] == 2021].copy()
df_taxe_2020['annee_cible'] = 2020

df_taxe_fonciere = pd.concat([df_taxe_fonciere, df_taxe_2020], ignore_index=True)

df_merged['dep_code'] = df_merged['dep_code'].astype(str).str.zfill(2)
df_taxe_fonciere['dept'] = df_taxe_fonciere['dept'].astype(str).str.zfill(2)

df_merged['annee'] = df_merged['annee'].astype(int)
df_taxe_fonciere['annee_cible'] = df_taxe_fonciere['annee_cible'].astype(int)

print(df_taxe_fonciere['annee_cible'].value_counts().sort_index())

annee_cible
2020    101
2021    101
2022    101
2023    101
2024    101
2025    101
Name: count, dtype: int64

In [117]:
df_merged = df_merged.merge(
    df_taxe_fonciere[['dept', 'annee_cible', 'taux_global_tfb', 'taux_global_tfnb', 'taux_plein_teom', 'taux_global_th']],
    left_on=['dep_code', 'annee'],
    right_on=['dept', 'annee_cible'],
    how='left'
)

In [118]:
df_merged.shape

(195290, 24)

In [119]:
df_merged.tail(10)

,code_commune,annee,prix_m2,surface_reelle_bati,nb_ventes,code_insee,nom_standard,code_postal,dep_code,dep_nom,...,superficie_km2,latitude_centre,longitude_centre,zone_emploi,dept,annee_cible,taux_global_tfb,taux_global_tfnb,taux_plein_teom,taux_global_th
195280,30346,2025,2703.336031,137.428571,26,30346,Vers-Pont-du-Gard,30210.0,30,Gard,...,19.0,43.967,4.520,7618.0,30,2025.0,54.01,142.18,11.71,41.37
195281,30347,2025,3723.894145,84.666667,12,30347,Vestric-et-Candiac,30600.0,30,Gard,...,11.0,43.736,4.264,7618.0,30,2025.0,54.01,142.18,11.71,41.37
195282,30348,2025,3222.459513,107.222222,31,30348,Vézénobres,30360.0,30,Gard,...,17.0,44.051,4.135,7603.0,30,2025.0,54.01,142.18,11.71,41.37
195283,30349,2025,2974.358974,117.000000,10,30349,Vic-le-Fesq,30260.0,30,Gard,...,10.0,43.868,4.077,7618.0,30,2025.0,54.01,142.18,11.71,41.37
195284,30350,2025,1146.378514,72.750000,68,30350,Le Vigan,30120.0,30,Gard,...,17.0,43.989,3.625,7603.0,30,2025.0,54.01,142.18,11.71,41.37
195285,30351,2025,3717.700974,95.454545,145,30351,Villeneuve-lès-Avignon,30400.0,30,Gard,...,18.0,43.977,4.795,53.0,30,2025.0,54.01,142.18,11.71,41.37
195286,30352,2025,3113.750937,110.130435,61,30352,Villevieille,30250.0,30,Gard,...,8.0,43.796,4.101,7618.0,30,2025.0,54.01,142.18,11.71,41.37
195287,30354,2025,2230.434783,230.000000,6,30354,Montagnac,30350.0,30,Gard,...,9.0,43.938,4.153,7618.0,30,2025.0,54.01,142.18,11.71,41.37
195288,30355,2025,2579.066284,99.857143,15,30355,Saint-Paul-les-Fonts,30330.0,30,Gard,...,5.0,44.076,4.617,7605.0,30,2025.0,54.01,142.18,11.71,41.37
195289,30356,2025,5666.725967,76.904762,39,30356,Rodilhan,30230.0,30,Gard,...,5.0,43.826,4.434,7618.0,30,2025.0,54.01,142.18,11.71,41.37

In [120]:
df_merged[['dept', 'annee_cible', 'taux_global_tfb', 'taux_global_tfnb', 'taux_plein_teom', 'taux_global_th']].info()

<class 'pandas.DataFrame'>
RangeIndex: 195290 entries, 0 to 195289
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   dept              195215 non-null  str
 1   annee_cible       195215 non-null  float64
 2   taux_global_tfb   195215 non-null  float64
 3   taux_global_tfnb  195215 non-null  float64
 4   taux_plein_teom   183235 non-null  float64
 5   taux_global_th    195215 non-null  float64
dtypes: float64(5), str(1)
memory usage: 8.9 MB

In [121]:
df_merged.head()

,code_commune,annee,prix_m2,surface_reelle_bati,nb_ventes,code_insee,nom_standard,code_postal,dep_code,dep_nom,...,superficie_km2,latitude_centre,longitude_centre,zone_emploi,dept,annee_cible,taux_global_tfb,taux_global_tfnb,taux_plein_teom,taux_global_th
0,01001,2020,1508.351938,132.857143,15,01001,L'Abergement-Clémenciat,1400.0,01,Ain,...,16.0,46.153,4.926,8405.0,01,2020.0,38.81,118.52,9.95,28.64
1,01002,2020,2022.908835,47.000000,10,01002,L'Abergement-de-Varey,1640.0,01,Ain,...,9.0,46.009,5.428,8405.0,01,2020.0,38.81,118.52,9.95,28.64
2,01004,2020,2530.613622,91.926136,433,01004,Ambérieu-en-Bugey,1500.0,01,Ain,...,24.0,45.961,5.373,8405.0,01,2020.0,38.81,118.52,9.95,28.64
3,01005,2020,3277.989223,105.478261,57,01005,Ambérieux-en-Dombes,1330.0,01,Ain,...,16.0,45.996,4.912,8434.0,01,2020.0,38.81,118.52,9.95,28.64
4,01006,2020,2326.979167,110.000000,12,01006,Ambléon,1300.0,01,Ain,...,6.0,45.750,5.594,8404.0,01,2020.0,38.81,118.52,9.95,28.64

In [122]:
df_merged.columns

Index(['code_commune', 'annee', 'prix_m2', 'surface_reelle_bati', 'nb_ventes',
       'code_insee', 'nom_standard', 'code_postal', 'dep_code', 'dep_nom',
       'reg_code', 'reg_nom', 'population', 'densite', 'superficie_km2',
       'latitude_centre', 'longitude_centre', 'zone_emploi', 'dept',
       'annee_cible', 'taux_global_tfb', 'taux_global_tfnb', 'taux_plein_teom',
       'taux_global_th'],
      dtype='str')

In [123]:
vf_annee = df_merged.groupby(['annee', 'code_commune'], dropna=False).agg(
    prix_m2=('prix_m2', 'mean'),
    dep_code=('dep_code', 'first'),
    dep_nom=('dep_nom', 'first'),
    reg_code=('reg_code', 'first'),
    reg_nom=('reg_nom', 'first'),
    code_postal=('code_postal', 'first'),
    population=('population', 'sum'),
    superficie_km2=('superficie_km2', 'sum'),  
    zone_emploi=('zone_emploi', 'first'),
    taux_global_tfb=('taux_global_tfb', 'mean'),
    taux_global_tfnb=('taux_global_tfnb', 'mean'),
    taux_plein_teom=('taux_plein_teom', 'mean'),
    taux_global_th=('taux_global_th', 'mean'),
    nb_ventes=('nb_ventes', 'sum')
).reset_index()

vf_annee = vf_annee.sort_values(['code_commune', 'annee'])
vf_annee['variation'] = vf_annee.groupby('code_commune')['prix_m2'].pct_change()
vf_annee = vf_annee[vf_annee['annee'] != 2020].reset_index(drop=True)

def market_trend(x, seuil=0.03):  
    if x > seuil:
        return 'hausse'
    elif x < -seuil:
        return 'baisse'
    else:
        return 'stable'
    
vf_annee['y'] = vf_annee['variation'].apply(market_trend)

In [18]:
vf_annee.shape

(161708, 17)

In [124]:
df_inflation = pd.read_csv(taux_inflation, sep=';', parse_dates=['Date'])
print(df_inflation.columns.tolist())
df_inflation.rename(columns={"Taux d’inflation": "taux_inflation"}, inplace=True)

['Date', 'Taux d’inflation']

In [125]:
df_inflation['annee'] = df_inflation['Date'].dt.year
df_inflation['taux_inflation'] = df_inflation["taux_inflation"] / 100

In [126]:
df_inflation['taux_inflation']

0     0.007
1     0.008
2     0.008
3     0.011
4     0.008
      ...
67    0.004
68    0.004
69    0.008
70    0.016
71    0.017
Name: taux_inflation, Length: 72, dtype: float64

In [127]:
inflation_par_annee = (
    df_inflation
    .sort_values('Date')
    .groupby('annee')['taux_inflation']
    .last()        
    .to_dict()
)

if 2025 not in inflation_par_annee:
    inflation_par_annee[2025] = inflation_par_annee[2024]
    
vf_annee['taux_inflation'] = vf_annee['annee'].map(inflation_par_annee)


"""
def market_trend_dynamic(row):
    x = row['variation']       
    seuil = row['taux_inflation']  

    if pd.isna(x) or pd.isna(seuil):
        return None

    if x > seuil:
        # Le prix augmente AU-DELÀ de l'inflation → hausse réelle
        return 'hausse'
    elif x < - seuil :
        # Le prix baisse en valeur nominale → baisse réelle (peu importe l'inflation)
        return 'baisse'
    else:
        # Le prix augmente mais moins que l'inflation → stable en termes réels
        return 'stable'

vf_annee['y'] = vf_annee.apply(market_trend_dynamic, axis=1)

"""

"\ndef market_trend_dynamic(row):\n    x = row['variation']       \n    seuil = row['taux_inflation']  \n\n    if pd.isna(x) or pd.isna(seuil):\n        return None\n\n    if x > seuil:\n        # Le prix augmente AU-DELÀ de l'inflation → hausse réelle\n        return 'hausse'\n    elif x < - seuil :\n        # Le prix baisse en valeur nominale → baisse réelle (peu importe l'inflation)\n        return 'baisse'\n    else:\n        # Le prix augmente mais moins que l'inflation → stable en termes réels\n        return 'stable'\n\nvf_annee['y'] = vf_annee.apply(market_trend_dynamic, axis=1)\n\n"

In [128]:
vf_annee.head(10)

,annee,code_commune,prix_m2,dep_code,dep_nom,reg_code,reg_nom,code_postal,population,superficie_km2,zone_emploi,taux_global_tfb,taux_global_tfnb,taux_plein_teom,taux_global_th,nb_ventes,variation,y,taux_inflation
0,2021,01001,2570.672952,01,Ain,84.0,Auvergne-Rhône-Alpes,1400.0,779.0,16.0,8405.0,38.81,118.52,9.95,28.64,58,0.704293,hausse,0.034
1,2022,01001,2930.586507,01,Ain,84.0,Auvergne-Rhône-Alpes,1400.0,779.0,16.0,8405.0,38.82,118.47,9.95,28.63,43,0.140008,hausse,0.067
2,2023,01001,3220.607801,01,Ain,84.0,Auvergne-Rhône-Alpes,1400.0,806.0,16.0,8405.0,38.82,118.53,9.95,28.62,42,0.098964,hausse,0.041
3,2024,01001,3248.685531,01,Ain,84.0,Auvergne-Rhône-Alpes,1400.0,806.0,16.0,8405.0,40.25,121.52,9.95,29.62,29,0.008718,stable,0.018
4,2025,01001,2890.639061,01,Ain,84.0,Auvergne-Rhône-Alpes,1400.0,832.0,16.0,8405.0,40.25,121.52,9.95,29.62,19,-0.110213,baisse,0.007
5,2021,01002,2878.541522,01,Ain,84.0,Auvergne-Rhône-Alpes,1640.0,256.0,9.0,8405.0,38.81,118.52,9.95,28.64,37,0.422971,hausse,0.034
6,2022,01002,2575.603876,01,Ain,84.0,Auvergne-Rhône-Alpes,1640.0,256.0,9.0,8405.0,38.82,118.47,9.95,28.63,24,-0.105240,baisse,0.067
7,2023,01002,1889.483901,01,Ain,84.0,Auvergne-Rhône-Alpes,1640.0,262.0,9.0,8405.0,38.82,118.53,9.95,28.62,18,-0.266392,baisse,0.041
8,2024,01002,1941.558442,01,Ain,84.0,Auvergne-Rhône-Alpes,1640.0,262.0,9.0,8405.0,40.25,121.52,9.95,29.62,26,0.027560,stable,0.018
9,2025,01002,1016.358651,01,Ain,84.0,Auvergne-Rhône-Alpes,1640.0,267.0,9.0,8405.0,40.25,121.52,9.95,29.62,46,-0.476524,baisse,0.007

In [129]:
vf_annee.columns

Index(['annee', 'code_commune', 'prix_m2', 'dep_code', 'dep_nom', 'reg_code',
       'reg_nom', 'code_postal', 'population', 'superficie_km2', 'zone_emploi',
       'taux_global_tfb', 'taux_global_tfnb', 'taux_plein_teom',
       'taux_global_th', 'nb_ventes', 'variation', 'y', 'taux_inflation'],
      dtype='str')

In [130]:
vf_annee.shape

(161708, 19)

In [79]:
df_emploi = pd.read_csv(nbr_emploi_par_region, sep=',', skiprows=3, header=0)
df_emploi = df_emploi.rename(columns={'Unnamed: 0': 'reg_nom'})

df_emploi = df_emploi.rename(columns={
    'Emploi total': 'emploi_total',
    'Emploi non salarié': 'emploi_non_salarie',
    'Emploi salarié': 'emploi_salarie',
    'Agriculture': 'part_agriculture',
    'Industrie': 'part_industrie',
    'Construction': 'part_construction',
    'Tertiaire marchand': 'part_tertiaire_marchand',
    'Tertiaire non marchand': 'part_tertiaire_non_marchand'
})

In [80]:
df_emploi.head()

,reg_nom,emploi_total,emploi_non_salarie,emploi_salarie,part_agriculture,part_industrie,Construction,part_tertiaire_marchand,part_tertiaire_non_marchand
0,Auvergne-Rhône-Alpes,"3,649",431,"3,219",1.0,15.0,6.0,48.0,30.0
1,Bourgogne-Franche-Comté,"1,115",128,988,2.0,17.0,5.0,41.0,35.0
2,Bretagne,"1,458",175,"1,282",2.0,14.0,6.0,44.0,33.0
3,Centre-Val de Loire,"1,043",109,933,1.0,16.0,6.0,44.0,33.0
4,Corse,142,22,120,3.0,6.0,10.0,43.0,38.0

In [81]:
print("vf_annee reg_nom:")
print(sorted(vf_annee['reg_nom'].dropna().unique()))

vf_annee reg_nom:
['Auvergne-Rhône-Alpes', 'Bourgogne-Franche-Comté', 'Bretagne', 'Centre-Val de Loire', 'Corse', 'Grand Est', 'Guadeloupe', 'Guyane', 'Hauts-de-France', 'La Réunion', 'Martinique', 'Normandie', 'Nouvelle-Aquitaine', 'Occitanie', 'Pays de la Loire', "Provence-Alpes-Côte d'Azur", 'Île-de-France']

In [82]:
print("\ndf_emploi reg_nom:")
print(sorted(df_emploi['reg_nom'].dropna().unique()))

df_emploi reg_nom:
['Auvergne-Rhône-Alpes', 'Bourgogne-Franche-Comté', 'Bretagne', 'Centre-Val de Loire', 'Champ\xa0: France hors Mayotte.', 'Corse', 'France hors Mayotte', 'Grand Est', 'Guadeloupe', 'Guyane', 'Hauts-de-France', 'La Réunion', 'Lecture\xa0: fin 2021, 3,6 millions de personnes sont en emploi en Auvergne-Rhône-Alpes, dont 3,2 millions de salariés\xa0; parmi ces derniers, 48\xa0% sont salariés du tertiaire marchand.', 'Martinique', 'Normandie', 'Nouvelle-Aquitaine', 'Occitanie', 'Pays de la Loire', "Provence-Alpes-Côte d'Azur", 'Source\xa0: Insee, Estimations d’emploi.', 'Île-de-France']

In [83]:
regions_valides = vf_annee['reg_nom'].dropna().unique()
df_emploi = df_emploi[df_emploi['reg_nom'].isin(regions_valides)].reset_index(drop=True)

print(df_emploi['reg_nom'].unique())
print(df_emploi.shape)

<StringArray>
[      'Auvergne-Rhône-Alpes',    'Bourgogne-Franche-Comté',
                   'Bretagne',        'Centre-Val de Loire',
                      'Corse',                  'Grand Est',
            'Hauts-de-France',              'Île-de-France',
                  'Normandie',         'Nouvelle-Aquitaine',
                  'Occitanie',           'Pays de la Loire',
 'Provence-Alpes-Côte d'Azur',                 'Guadeloupe',
                     'Guyane',                 'La Réunion',
                 'Martinique']
Length: 17, dtype: str
(17, 9)

In [84]:
print(df_emploi.columns.tolist())

['reg_nom', 'emploi_total', 'emploi_non_salarie', 'emploi_salarie', 'part_agriculture', 'part_industrie', 'Construction ', 'part_tertiaire_marchand', 'part_tertiaire_non_marchand']

In [85]:
vf_annee = vf_annee.merge(
    df_emploi,
    on='reg_nom',
    how='left'
)

In [86]:
vf_annee.shape

(161708, 27)

In [87]:
print(vf_annee['reg_nom'].isna().sum())
print(vf_annee['y'].isna().sum())
print(vf_annee.shape)

69
0
(161708, 27)

In [88]:
vf_annee.columns

Index(['annee', 'code_commune', 'prix_m2', 'dep_code', 'dep_nom', 'reg_code',
       'reg_nom', 'code_postal', 'population', 'superficie_km2', 'zone_emploi',
       'taux_global_tfb', 'taux_global_tfnb', 'taux_plein_teom',
       'taux_global_th', 'nb_ventes', 'variation', 'y', 'taux_inflation',
       'emploi_total', 'emploi_non_salarie', 'emploi_salarie',
       'part_agriculture', 'part_industrie', 'Construction ',
       'part_tertiaire_marchand', 'part_tertiaire_non_marchand'],
      dtype='str')

In [89]:
df_osm = pd.read_csv(osm_france)

In [90]:
df_osm[(df_osm["lat"].isna()) | (df_osm["lon"].isna())]

Empty DataFrame
Columns: [osm_id, lat, lon, name, amenity, railway, shop, leisure, code_postal, category, region]
Index: []

In [91]:
df_osm["code_postal"].isna().sum()

np.int64(151236)

In [92]:
print(df_osm.columns)
print("Données brutes : ", df_osm.shape)

Index(['osm_id', 'lat', 'lon', 'name', 'amenity', 'railway', 'shop', 'leisure',
       'code_postal', 'category', 'region'],
      dtype='str')
Données brutes :  (179050, 11)

In [93]:
df_osm["region"].unique()

<StringArray>
[             'Île-de-France',       'Auvergne-Rhône-Alpes',
         'Nouvelle-Aquitaine',                  'Occitanie',
            'Hauts-de-France',                  'Grand Est',
 'Provence-Alpes-Côte d'Azur',                  'Normandie',
                   'Bretagne',           'Pays de la Loire',
    'Bourgogne-Franche-Comté',        'Centre-Val de Loire']
Length: 12, dtype: str

In [94]:
df_osm["lat"] = pd.to_numeric(df_osm["lat"], errors="coerce")
df_osm["lon"] = pd.to_numeric(df_osm["lon"], errors="coerce")

df_osm = df_osm[
    (df_osm["lat"].between(41.0, 51.5)) &
    (df_osm["lon"].between(-5.5, 9.5))
]

print("🇫Après filtre France :", df_osm.shape)

🇫Après filtre France : (179042, 11)

In [95]:
df_osm.duplicated(subset=["lat", "lon"]).sum()

np.int64(99)

In [96]:
df_osm = df_osm.dropna(subset=["lat", "lon"])

In [97]:
df_osm.head(100)

,osm_id,lat,lon,name,amenity,railway,shop,leisure,code_postal,category,region
0,26697176,49.114908,2.281098,Mairie de Presles,townhall,NaN,NaN,NaN,95590,admin_sante,Île-de-France
1,27362211,48.726417,2.049171,Mairie de Milon-la-Chapelle,townhall,NaN,NaN,NaN,78470,admin_sante,Île-de-France
2,139222605,48.742226,2.225964,Mairie d'Igny,townhall,NaN,NaN,NaN,91430,admin_sante,Île-de-France
3,242922184,48.941072,2.158363,Mairie de Sartrouville,townhall,NaN,NaN,NaN,78500,admin_sante,Île-de-France
4,269306155,48.800668,2.262543,Mairie de Clamart,townhall,NaN,NaN,NaN,92140,admin_sante,Île-de-France
...,...,...,...,...,...,...,...,...,...,...,...
95,1473359379,48.689076,2.115691,Mairie Annexe,townhall,NaN,NaN,NaN,91190,admin_sante,Île-de-France
96,1475296413,48.378203,2.794777,Mairie déléguée de Veneux-les-Sablons,townhall,NaN,NaN,NaN,77250,admin_sante,Île-de-France
97,1505745193,48.781495,3.305758,Hôtel de Ville,townhall,NaN,NaN,NaN,NaN,admin_sante,Île-de-France
98,1506143575,48.694476,1.854474,Mairie du Perray-en-Yvelines,townhall,NaN,NaN,NaN,78610,admin_sante,Île-de-France
99,1512016470,48.509594,3.200806,Mairie de Savins,townhall,NaN,NaN,NaN,NaN,admin_sante,Île-de-France

In [98]:
CATEGORY_COLS = {
    "admin_sante":      "amenity",
    "education":        "amenity",
    "transports_rails": "railway",
    "commerces_malls":  "shop",
    "loisirs_verts":    "leisure",
}

for cat, col in CATEGORY_COLS.items():
    df_cat = df_osm[df_osm["category"] == cat]
    print(f"\n{cat} (colonne: '{col}')")
    print(df_cat[col].value_counts().to_string())

admin_sante (colonne: 'amenity')
amenity
townhall                           36869
hospital                            2451
library;townhall;arts_center           1
townhall;bicycle_repair_station        1

education (colonne: 'amenity')
amenity
school                                        63315
driving_school                                 5065
college                                        3096
university                                     1722
music_school                                   1610
language_school                                 250
dancing_school                                  242
ski_school                                      135
prep_school                                     134
surf_school                                      56
sailing_school                                   37
art_school                                       18
boat_school                                      14
cooking_school                                   13
flight_school                                    10
professional_school                              10
school:FR                                         7
sport_school                                      4
painting_school                                   2
circus_school                                     2
trade_school                                      2
boatdriving_school                                2
music_school;dancing_school;theatre_school        1
drama_school                                      1
kitchen_school                                    1
arts_centre;music_school                          1
education:university                              1
brothel;school                                    1
theatre_school                                    1
beauty_school                                     1
flight school                                     1
surf_school;sail_school                           1
flying_school                                     1
scuba_diving_school                               1
diving_school                                     1
was:school                                        1

transports_rails (colonne: 'railway')
railway
train_station_entrance                    4462
station                                   2934
subway_entrance                           2139
disused_station                             43
service_station                             21
subway_entrance;train_station_entrance       2
technical_station                            2
emergency_subway_entrance                    1
service_station;halt                         1
train_station                                1

commerces_malls (colonne: 'shop')
shop
supermarket                                      15507
mall                                              1361
convenience;supermarket;greengrocer;farm;deli        5
small_electric_vehicle                               3
convenience;supermarket;farm;greengrocer;deli        3
supermarket;bakery                                   1
supermarket;convenience                              1
wholesale;supermarket                                1
supermarket;interior_decoration                      1
convenience;supermarket                              1

loisirs_verts (colonne: 'leisure')
leisure
park    37470

In [99]:
agg_region = (
    df_osm
    .groupby(["region", "category"])
    .size()
    .unstack(fill_value=0)
    .reset_index()
)

In [100]:
output_path = os.path.join('raw', f'csv_osm.csv')
agg_region.to_csv(output_path, index=False, sep=';', encoding='utf-8')

In [101]:
vf_annee

,annee,code_commune,prix_m2,dep_code,dep_nom,reg_code,reg_nom,code_postal,population,superficie_km2,...,y,taux_inflation,emploi_total,emploi_non_salarie,emploi_salarie,part_agriculture,part_industrie,Construction,part_tertiaire_marchand,part_tertiaire_non_marchand
0,2021,01001,2570.672952,01,Ain,84.0,Auvergne-Rhône-Alpes,1400.0,779.0,16.0,...,hausse,0.034,"3,649",431,"3,219",1.0,15.0,6.0,48.0,30.0
1,2022,01001,2930.586507,01,Ain,84.0,Auvergne-Rhône-Alpes,1400.0,779.0,16.0,...,hausse,0.067,"3,649",431,"3,219",1.0,15.0,6.0,48.0,30.0
2,2023,01001,3220.607801,01,Ain,84.0,Auvergne-Rhône-Alpes,1400.0,806.0,16.0,...,hausse,0.041,"3,649",431,"3,219",1.0,15.0,6.0,48.0,30.0
3,2024,01001,3248.685531,01,Ain,84.0,Auvergne-Rhône-Alpes,1400.0,806.0,16.0,...,stable,0.018,"3,649",431,"3,219",1.0,15.0,6.0,48.0,30.0
4,2025,01001,2890.639061,01,Ain,84.0,Auvergne-Rhône-Alpes,1400.0,832.0,16.0,...,baisse,0.007,"3,649",431,"3,219",1.0,15.0,6.0,48.0,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161703,2021,97424,3292.954188,974,La Réunion,4.0,La Réunion,97413.0,5538.0,84.0,...,hausse,0.034,325,41,284,1.0,7.0,6.0,44.0,42.0
161704,2022,97424,1995.206083,974,La Réunion,4.0,La Réunion,97413.0,5538.0,84.0,...,baisse,0.067,325,41,284,1.0,7.0,6.0,44.0,42.0
161705,2023,97424,5794.669289,974,La Réunion,4.0,La Réunion,97413.0,5568.0,84.0,...,hausse,0.041,325,41,284,1.0,7.0,6.0,44.0,42.0
161706,2024,97424,4027.572082,974,La Réunion,4.0,La Réunion,97413.0,5568.0,84.0,...,baisse,0.018,325,41,284,1.0,7.0,6.0,44.0,42.0
161707,2025,97424,2181.029396,974,La Réunion,4.0,La Réunion,97413.0,5390.0,84.0,...,baisse,0.007,325,41,284,1.0,7.0,6.0,44.0,42.0

In [102]:
df_merged = vf_annee.merge(
    agg_region,
    left_on="reg_nom",
    right_on="region",
    how="left"
)

In [103]:
vf_annee.shape

(161708, 27)

In [104]:
df_merged.shape

(161708, 33)

In [105]:
df_merged['y'].value_counts()

y
hausse    71670
baisse    65812
stable    24226
Name: count, dtype: int64

In [106]:
df_merged[df_merged['annee'] == 2025 ]['y'].value_counts()

y
baisse    13323
hausse    10554
stable     6382
Name: count, dtype: int64

In [ ]:
output_path = os.path.join('raw', f'csv_full_post2.csv')
df_merged.to_csv(output_path, index=False, sep=';', encoding='utf-8')